repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch
    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1
  hooks:
      # Terraform
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_providers_lock
      args:
        - --tf-init-args=-upgrade
    - id: terraform_docs
      args:
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terrascan
      args:
        # Skip stupid "Ensure that Azure Resource Group has resource lock enabled" rule.
        - --args=--skip-rules="accurics.azure.NS.272"
    - id: infracost_breakdown
      args:
        - --args=--path=./
        - --hook-config='.projects[].diff.totalMonthlyCost|tonumber != 100'
        - --hook-config='.currency == "USD"'
      verbose: true # Always show costs